name: build

on:
  push:
    branches: [ main, testing-ci ]
    tags-ignore:
      - 'v*.*.*'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
    - name: Run tests
      run: make test
    - name: Lint programs
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true
  build-for-linux:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=version::$VERSION
      - name: Build platform binary
        run: VERSION=${{ steps.version.outputs.version }} make linux
  build-for-darwin:
    runs-on: macos-12
    needs: test-and-lint
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=version::$VERSION
      - name: Build platform binary
        run: VERSION=${{ steps.version.outputs.version }} make darwin-deps darwin
