name: CI testing

on:
  push:
    branches: [ main ]
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run tests
      run: make test
    - name: Lint programs
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41
