name: build

on:
  push:
    branches: [ main, testing-ci ]
    tags-ignore:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.17.5
    - name: Run tests
      run: make test
    - name: Lint programs
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true
